# Alpine Linux with OpenJDK JRE
#FROM openjdk:19-jdk-slim-buster
## copy WAR into image
#COPY spring-boot-app-0.0.1-SNAPSHOT.war /app.jar
## run application with this command line
#CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=default", "/app.war"]